#!/usr/bin/env python3
"""Regenerate rom/spec_es.lua from the EUR (Spanish) import manifests.

The manifests are the ones tools/make_es_manifest.py derives from the
shift-matching einstein95/pokered-es disassembly (gen1recomp PR #622); this
script trims them down to what the mod's runtime decoder needs: the dialogue
label addresses, their dynamic-substitution metadata, the charmap, and the
four name tables. Red and Blue share one layout (the manifests differ only
in romSha1), so a single spec carries both with two accepted hashes.

Usage:
  python3 build_spec.py rom_manifest_red_es.json rom_manifest_blue_es.json \
      > ../rom/spec_es.lua

Nothing in the output is ROM content: addresses, ids and the byte->glyph
charmap only, same posture as the import manifests themselves.
"""

import json
import sys

# (symbol, manifest path to the id order, fixed cell width, registry id
# prefix -- the trainer registry keys classes as OPP_<label>)
NAME_TABLES = {
    "moves":    ("MoveNames",    ("constants", "moveOrder"), None, ""),
    "items":    ("ItemNames",    ("items",),                 None, ""),
    "trainers": ("TrainerNames", ("trainers",),              None, "OPP_"),
    "species":  ("MonsterNames", ("constants", "speciesOrder"), 10, ""),
}

ROMS = [
    ("red",  "Pokemon Edicion Roja"),
    ("blue", "Pokemon Edicion Azul"),
]


def lua_quote(text):
    out = text.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return '"%s"' % out


def get_path(manifest, path):
    value = manifest
    for key in path:
        value = value[key]
    return value


def main(red_path, blue_path):
    red = json.load(open(red_path, encoding="utf-8"))
    blue = json.load(open(blue_path, encoding="utf-8"))

    # The spec only consumes these keys; red and blue may differ elsewhere
    # (romSha1, and version-specific `field` data like preset names).
    for key in ("symbols", "text", "charmap", "constants", "items", "trainers"):
        if red[key] != blue[key]:
            sys.exit("build_spec: red and blue manifests differ in %r; "
                     "a shared spec is no longer valid" % key)

    m = red
    symbols = m["symbols"]
    labels = sorted(m["text"]["labels"])
    dynamic = m["text"]["dynamic"]

    missing = [l for l in labels if l not in symbols]
    if missing:
        sys.exit("build_spec: %d dialogue labels have no symbol, e.g. %s"
                 % (len(missing), missing[:3]))

    w = sys.stdout.write
    w("-- Generated by tools/build_spec.py -- do not edit by hand.\n")
    w("-- Source: the EUR (Spanish) import manifests derived from the\n")
    w("-- shift-matching einstein95/pokered-es disassembly (PR #622).\n")
    w("-- Addresses, ids and the byte->glyph charmap only; no ROM content.\n")
    w("return {\n")

    w("  roms = {\n")
    for (game, label), path in zip(ROMS, (red_path, blue_path)):
        rom = json.load(open(path, encoding="utf-8"))
        presets = rom["field"]["presetNames"]
        w('    { sha1 = %s, game = %s, label = %s,\n'
          % (lua_quote(rom["romSha1"]), lua_quote(game), lua_quote(label)))
        w('      presets = { player = { %s }, rival = { %s } } },\n'
          % (", ".join(lua_quote(x) for x in presets["player"]),
             ", ".join(lua_quote(x) for x in presets["rival"])))
    w("  },\n")

    w("  charmap = {\n")
    for key in sorted(m["charmap"], key=int):
        glyph = m["charmap"][key]
        w("    [%d] = %s,\n" % (int(key), lua_quote(glyph)))
    w("  },\n")

    w("  dialogue = {\n")
    for label in labels:
        bank, address = symbols[label]
        w("    [%s] = { %d, %d },\n" % (lua_quote(label), bank, address))
    w("  },\n")

    w("  dynamic = {\n")
    for label in sorted(dynamic):
        subs = ", ".join(
            "{ %d, %s }" % (cmd, lua_quote(repl))
            for cmd, repl in dynamic[label])
        w("    [%s] = { %s },\n" % (lua_quote(label), subs))
    w("  },\n")

    # the EUR dex table: per-species kind + official metric height/weight.
    # PokedexEntryPointers is indexed by internal species index (the
    # MonsterNames order), not by dex number.
    dex_bank, dex_address = symbols["PokedexEntryPointers"]
    w("  dex = {\n")
    w("    bank = %d, address = %d,\n" % (dex_bank, dex_address))
    w("    order = { %s },\n"
      % ", ".join(lua_quote(entry)
                  for entry in get_path(m, ("constants", "speciesOrder"))))
    w("  },\n")

    w("  types = {\n")
    for label in m["typeNameLabels"]:
        tid = label.split(".")[-1].upper()
        if tid == "PSYCHIC":
            tid = "PSYCHIC_TYPE"
        bank, address = symbols[label]
        w("    { id = %s, bank = %d, address = %d },\n"
          % (lua_quote(tid), bank, address))
    w("  },\n")

    # graphic sheets the cartridge layer re-derives at runtime (same
    # symbols, sizes and flags as the importer's own extraction)
    w("  gfx = {\n")
    for key, symbol in (("font", "FontGraphics"),
                        ("hpbar", "HpBarAndStatusGraphics"),
                        ("hud1", "BattleHudTiles1"),
                        ("hud2", "BattleHudTiles2"),
                        ("hud3", "BattleHudTiles3"),
                        ("version", "Version_GFX")):
        bank, address = symbols[symbol]
        w("    %s = { bank = %d, address = %d },\n" % (key, bank, address))
    w("  },\n")

    w("  names = {\n")
    for key in sorted(NAME_TABLES):
        symbol_name, order_path, width, prefix = NAME_TABLES[key]
        bank, address = symbols[symbol_name]
        order = get_path(m, order_path)
        w("    %s = {\n" % key)
        w("      bank = %d, address = %d,%s\n"
          % (bank, address, (" width = %d," % width) if width else ""))
        w("      order = { %s },\n"
          % ", ".join(lua_quote(prefix + entry) for entry in order))
        w("    },\n")
    w("  },\n")

    w("}\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip())
    main(sys.argv[1], sys.argv[2])
